### ISSUE TITLE
peer review week 1

### ISSUE THREAD

**Issue by SharonV33** [lisaoude/Gifinder#1]
## Algemeen
Nog geen app beschrijving in de readme, overall structuur is netjes en de github pages link werkt. 👍🏻
Je zou nog even kunnen kijken naar het geven van een beschrijving van een commit. Op die manier kan je makkelijk zien wat er in die commit allemaal veranderd is, als je alleen werkt niet super relevant maar heel handig in een team  

## HTML
HTML is semantisch correct, je zou eventueel je gifContainer in een section veranderen. 

## CSS
Er is nog geen duidelijk ontwerp maar de CSS die er is ziet er netjes uit 

## JS
Opbouw is logisch, er staan geen comments in wat kan helpen met het begrijpen van de code voor jou en andere. Verder erg netjes

**Comment by lisaoude** [comment]
# Algemeen 
- App beschrijving in de readme ga ik toevoegen!
- Beschrijving geven aan een commit is een goede tip, ga ik zeker toepassen!

# HTML
- Kan inderdaad een section worden, ga ik aanpassen.

# JS
- Comments wil ik inderdaad gaan toevoegen voor extra duidelijkheid.
