### ISSUE TITLE
Why render giphy in iframe?

### ISSUE THREAD

**Issue by joostf** [lisaoude/Gifinder#11]
https://github.com/lisaoude/web-app-from-scratch-2021/blob/221021ee2f54d108538b6d42a765bc8d44aa909a/js/modules/components/gifs.js#L3

**Comment by joostf** [comment]
please render the giphy's as images in the same document.

**Comment by lisaoude** [comment]
✅ fixed, rendered in iframe because i couldnt get images to work the first time - now all images!
