### ISSUE TITLE
Peer review - Live Demo

### ISSUE THREAD

**Issue by veerleprins** [lisaoude/Gifinder#17]
## Feedback
- There is no Actor Diagram and Interaction Diagram available yet so I have no idea if it matches your code. 😞 
- Based on your explanation in your README, it is clear what I could expect with your live demo. ✅ 
- I myself would have made the application a bit more exciting. But maybe you can still do this (even if it's small things) and maybe still focus on the styling? I know that you are good with styling and CSS ! 👍 👍 

## To Solve This Issue:
- [x] Make your site a bit more exciting (styling / general concept).

**Comment by lisaoude** [comment]
Styling and overall experience has been improved.
