### ISSUE TITLE
Peer review - repo

### ISSUE THREAD

**Issue by Chazzers** [lisaoude/Gifinder#19]
- [x] Link to demo
- [x] The description is a bit short on the concept
- [x] The used api is not described in the readme
- [x] Place an image of the actor and interaction diagrams in the readme

So usually what shouldn't be in a repo is your weekly log and the process of making your app. The readme must contain the following:

- Description of Concept
- If there is an API, description of API
- Actor and interaction diagram (this assignment)
- If you need to install this project, an installation guide i.e. `npm install` etc.
- Acknowledgments (shoutouts to the people who helped you make this)

The rest of your documentation should be placed inside a wiki

**Comment by lisaoude** [comment]
To Do:
- [x] Link to demo
- [x] Move weekly log to wiki
- [x] Improve and expand description of concept
- [x] Describe API in readme
- [x] Make actor diagram
- [x] Make interaction diagram
