### ISSUE TITLE
General Tip🤓🤓🤓🤓

### ISSUE THREAD

**Issue by Chazzers** [lisaoude/Gifinder#5]
:nerd_face:

If you're new to js, some function variables and parameters may be unfamiliar to you.

For example

```js
function (e)
```
means:

```js
function (event)
```
```js
fetch(url).then(res)
```
means:
```js
fetch(url).then(response)
```

**Comment by lisaoude** [comment]
Thanks for pointing this out to me! I wrote my JS with someone's help, and genuinely didn't kow what the random e meant :')
Will be changed, so I understand better!
