### ISSUE TITLE
Peer Review - Sanne 12 feb

### ISSUE THREAD

**Issue by sanneduinkerx** [lisaoude/Gifinder#7]
**Algemeen/repo**
- Read me goede manier om alles bij te houden! handig dat je een to do list voor jezelf hebt gemaakt. 
- Api/concept is beschreven en de link naar de live demo staat er ook! :)
- Je mist alleen nog een description bij de repo waar ook je link staat zeg maar. 
- Voor volgende keer: include actor en interaction diagram :)
- Live demo werkt, ik verwachtte precies wat ik dacht.

**Code**
- `const init` (in main.js) ik snap zelf de benaming init niet 😬, misschien dat je dat search noemt? dan wordt het iets duidelijker. 
- Verder ziet je code er netjes uit, ik snap wat er gebeurt! 😊 
- De actors zijn helder, main.js (zoeken naar specifieke gif), fetchData (haalt de data uit Api), printGifs (rendert data in html), die nu worden geïmporteerd naar main.
- Als tip misschien bovenin elke script bestand in module nog een comment aangeven wat er binnen dat script gebeurd. Handig voor jezelf voor later 😄  
- Code is consistent overal zelfde methode!

**Comment by lisaoude** [comment]
To Do:

- [x] Add description to 'about' section of repo
- [x] Make actor diagram
- [x] Make interaction diagram
- [x] Look into naming of 'const init'
- [x] Add some more comments in js files for clarity
