### ISSUE TITLE
Feedback 12 feb Lotte

### ISSUE THREAD

**Issue by Lottetekulve** [lisaoude/Gifinder#8]
Goede read me, alles staat er in. Als je in elements.js een functie maakt om je const's heen, dan hoef je alleen die functie te exporteren en niet al die variabelen. Zo heb ik t gedaan iig. Je fetchDtata.js ziet er goed uit. Goed dat je je link zo hebt opgesplitst in key, limit etc. Op je live demo werkt je zoek button maar een keer en je kan niet terug, dus miss een terug knop of een manier vinden om die zoek knop dan ook weer te laten werken. En als je nu naar je website gaat staat er geen content totdat je zoekt. Miss een meest populaire gifs lijst als 'home page'.

**Comment by lisaoude** [comment]
To Do:

- [x] Put a function around variables in elements.js to export them at once
- [x] Fix data showing in live demo (when you search a different word, the gifs show up underneath the previous result)
- [x] Show popular gifs before searching as a homepage

**Comment by lisaoude** [comment]
instead of a function around it, fixed like this 

```
export const
    url = 'https://api.giphy.com/v1/gifs/',
    searchType = 'search?q=',
    trendingType = 'trending',
    key = 'personalKey',
    limit = 5
```
