### ISSUE TITLE
Use a form element instead of a section

### ISSUE THREAD

**Issue by joostf** [lisaoude/Gifinder#9]
https://github.com/lisaoude/web-app-from-scratch-2021/blob/221021ee2f54d108538b6d42a765bc8d44aa909a/index.html#L23-L26

You gets submit functionality out of the box (which also works with the keaboard)

**Comment by lisaoude** [comment]
Done ✅

**Comment by lisaoude** [comment]
nvm it broke, fixing now 😢

**Comment by lisaoude** [comment]
✅ fixed by making sure the page doesn't reload on submitting with preventDefault!
